config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticated :user do
    root to: 'twiits#index', as: :authenticated_root
  end

  resources :users , only: [] do
    resources :profiles, only: %i[show edit update]
  end

  resources :twiits, only: %i[index show create destroy] do
    resources :replies, only: :create, module: :twiits
    resources :likes, only: %i[create destroy], module: :twiits
  end

  resources :replies, only: [] do
    resources :replies, only: :create, module: :replies
    resources :likes, only: %i[create], module: :replies
  end

  root to: 'homepage#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true

  validates :user_id, presence: true,
                      uniqueness: { scope: %i[likeable_id likeable_type], message: 'Já curtido' }
  validates :likeable_id, presence: true,
                          uniqueness: { scope: %i[user_id likeable_type], message: 'Já curtido' }
  validates :likeable_type, presence: true,
                            uniqueness: { scope: %i[user_id likeable_id], message: 'Já curtido' }
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :user
  belongs_to :replieable, polymorphic: true
  has_many :replies, dependent: :destroy, as: :replieable
  has_many :likes, dependent: :destroy, as: :likeable

  validates :user_id, :replieable_id, :body, presence: true
  validates :body, length: { in: 1..280 }
end

app/models/twiit.rb
class Twiit < ApplicationRecord
  belongs_to :user
  has_many :replies, dependent: :destroy, as: :replieable
  has_many :likes, dependent: :destroy, as: :likeable

  validates :user_id, presence: true
  validates :text, presence: true, length: { in: 1..280 }

  def owner?(current_user)
    user == current_user
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :twiits, dependent: :destroy
  has_many :replies, dependent: :destroy
  has_one :profile, dependent: :destroy
  has_many :likes, dependent: :destroy

  after_create :create_user_profile
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def like(likeable)
    likes.create!(likeable: likeable)
  end

  def unlike(likeable)
    likes.delete(Like.where(user: self, likeable: likeable))
  end

  def liked?(likeable)
    likes.map(&:likeable_id).include?(likeable.id)
  end

  private

  def create_user_profile
    create_profile!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protected

  def after_sign_in_path_for(_user)
    twiits_path
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index; end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    current_user.like(@likeable)

    redirect_back(fallback_location: root_path)
  end

  def destroy
    current_user.unlike(@likeable)

    redirect_back(fallback_location: root_path)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!, only: %i[show edit update]
  before_action :set_profile, only: %i[show edit update]

  def show; end

  def edit; end

  def update
    if @profile.update!(profile_params)
      redirect_to user_profile_path(@profile)
    else
      render 'edit'
    end
  end

  private

  def set_profile
    @profile = Profile.find(params[:id])
  end

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :bio)
  end
end

app/controllers/replies/likes_controller.rb
class Replies::LikesController < LikesController
  before_action :set_likeable

  private

  def set_likeable
    @likeable = Reply.find(params[:reply_id])
  end
end

app/controllers/replies/replies_controller.rb
class Replies::RepliesController < RepliesController
  before_action :set_replieable

  private

  def set_replieable
    @replieable = Reply.find(params[:reply_id])
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def create
    reply = @replieable.replies.build(reply_params)
    reply.user = current_user
    reply.save
    flash[:notice] = 'Resposta enviada'
    redirect_back(fallback_location: root_path)
  end

  private

  def reply_params
    params.require(:reply).permit(:body)
  end
end

app/controllers/twiits/likes_controller.rb
class Twiits::LikesController < LikesController
  before_action :set_likeable

  private

  def set_likeable
    @likeable = Twiit.find(params[:twiit_id])
  end
end

app/controllers/twiits/replies_controller.rb
class Twiits::RepliesController < RepliesController
  before_action :set_replieable

  private

  def set_replieable
    @replieable = Twiit.find(params[:twiit_id])
  end
end

app/controllers/twiits_controller.rb
class TwiitsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_twiit, only: %i[show destroy]

  def index
    @twiits = Twiit.all
    @twiit = Twiit.new
  end

  def show; end

  def create
    @twiit = current_user.twiits.build(twiit_params)

    if @twiit.save
      flash[:notice] = 'Postado'
    else
      flash[:error] = @twiit.errors.full_messages.first
    end

    redirect_back(fallback_location: root_path)
  end

  def destroy
    @twiit.destroy if @twiit.owner?(current_user)
    flash[:notice] = 'Deletado'
    redirect_back(fallback_location: root_path)
  end

  private

  def set_twiit
    @twiit = Twiit.find(params[:id])
  end

  def twiit_params
    params.require(:twiit).permit(:text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homepage/index.html.erb
<section class="homepage">
  <section class="homepage_actions">
    <h1>Saiba o que está acontecendo no mundo agora.</h1>

    <h4>Inscreva-se no Twiiter hoje mesmo.</h4>

    <%= link_to 'Inscrever-se', new_user_registration_path, class: 'btn-large custom-btn' %>
    <%= link_to 'Entrar', new_user_session_path, class: 'btn-large custom-btn-outline' %>
  </section>

  <section class="homepage_info">
    <h2><i class="material-icons">search</i> Siga o que for do seu interesse.</h2>
    <h2><i class="material-icons">people_outline</i> Saiba o que as pessoas estão falando.</h2>
    <h2><i class="material-icons">chat_bubble_outline</i> Participe da conversa</h2>
  </section>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twiiter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <% flash.each do |key, msg| %>
      <p class="<%= key %>"><%= msg %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/profiles/edit.html.erb
<%= form_with(model: [:user, @profile], local: true) do |form| %>
  <%= form.label :first_name, 'Nome' %>
  <%= form.text_field :first_name %>

  <%= form.label :last_name, 'Sobrenome' %>
  <%= form.text_field :last_name %>

  <%= form.label :bio, 'Bio' %>
  <%= form.text_area :bio %>

  <%= form.submit 'Enviar' %>
<% end %>

app/views/profiles/show.html.erb
<%= link_to 'Editar Perfil', edit_user_profile_path(current_user) if user_signed_in? %>

<%= @profile.first_name %>
<%= @profile.last_name %>
<%= @profile.bio %>

app/views/replies/_form.html.erb
<%= form_with(model: [replieable, Reply.new], local: true) do |form| %>
  <%= form.label :body %>
  <%= form.text_area :body %>
  <%= form.submit 'Enviar' %>
<% end %>

app/views/replies/_replies.html.erb
<% replieable.replies.each do |reply| %>
  <%= reply.body %>
<% end %>

app/views/replies/_reply.html.erb
<div class="reply">
  <%= replieable.body %>
  <%= link_to 'Like', reply_likes_path(replieable), method: :post %>
</div>

<%= render partial: 'replies/replies', locals: { replieable: replieable } %>

<div id="reply_for_reply_form">
  <%= render partial: 'replies/form', locals: { replieable: replieable } %>
</div>

app/views/twiits/index.html.erb
<section class="main_layout">

  <section class="mobile_menu_header">
    <ul id="slide-out" class="sidenav mobile_menu">
      <li><a href="#!">Second Link</a></li>
      <li><a href="#!">Second Link</a></li>
      <li><a href="#!">Second Link</a></li>
      <li><a href="#!">Second Link</a></li>
      <li><a class="waves-effect" href="#!">Third Link With Waves</a></li>
    </ul>
    <a href="#" data-target="slide-out" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    <h1>Página inicial</h1>
  </section>

  <section class="menu">
    <h2><i class="material-icons">home</i> <a href="#">Link</a></h2>
    <h2><i class="material-icons">home</i> <a href="#">Link</a></h2>
    <h2><i class="material-icons">home</i> <a href="#">Link</a></h2>
    <h2><i class="material-icons">home</i> <a href="#">Link</a></h2>
    <h2><i class="material-icons">home</i>
      <%= link_to 'Perfil', user_profile_path(current_user, current_user.profile) if user_signed_in? %>
    </h2>
  </section>

  <section class="feed">
    <div class="twiit_form">
      <%= form_with(model: @twiit, local: true) do |form| %>
        <div class="twiit_form_box" >
          <%= form.label :text, 'twiit' %>
          <%= form.text_area :text %>
          <%= form.submit 'TWIIT', class: 'btn custom-btn-outline' %>
        </div>
      <% end %>
    </div>

      <% @twiits.each do |twiit| %>
        <div class="twiit">
          <p><%= twiit.text %></p>
          <% if current_user.liked?(twiit) %>
            <%= link_to 'Unlike', twiit_like_path(twiit, twiit.id), method: :delete %>
          <% else %>
            <%= link_to 'Like', twiit_likes_path(twiit), method: :post %>
          <% end %>

          <%= link_to 'Delete twiit', twiit_path(twiit), 
            method: :delete if twiit.owner?(current_user) %>
        </div>
      <% end %>
  </section>

  <section class="menu_aside">
    <ul class="collection with-header custom-collection">
        <li class="collection-item"><h4>O que está acontecendo</h4></li>
        <li class="collection-item">Alvin</li>
        <li class="collection-item">Alvin</li>
        <li class="collection-item">Alvin</li>
        <li class="collection-item">Alvin</li>
      </ul>
  </section>

  <footer class="mobile_footer">
    <ul>
      <li><a href="#"><i class="material-icons">search</i></a></li>
      <li><a href="#"><i class="material-icons">home</i></a></li>
      <li><a href="#"><i class="material-icons">notifications</i></a></li>
      <li><a href="#"><i class="material-icons">mail</i></a></li>
    </ul>
  </footer>
</section>

app/views/twiits/show.html.erb
<%= @twiit.text %>

<%= render partial: 'replies/reply', collection: @twiit.replies, as: :replieable %>

<div id="reply_twiit_form">
  <%= render partial: 'replies/form', locals: { replieable: @twiit } %>
</div>